### ISSUE TITLE
Is 1.0.1 released?

### ISSUE THREAD

**Issue by Zordid** [arrow-kt/arrow#2577] opened 2021-11-09 21:57 UTC
I can only see it here, but not in "latest" releases. When I update my Maven POM dependency, my code does not compile anymore. Imports from all arrow. packages fail.

**Comment by nomisRev** [comment] 2021-11-09 22:13
Hey @Zordid,

There are some issues with publishing Kotlin MPP. In `1.0.0` it was missing Apple variants, and now  Maven support is broken. There is nothing new inside `1.0.1` so you can just continue to use `1.0.0` with Maven for now. This is being worked on atm and will be fixed soon.

That's why there is no release in Github. Thanks for opening the ticket, and using Arrow!

**Comment by Zordid** [comment] 2021-11-10 07:23
I made it work again by adding "-jvm" to all my artifact names... maybe this should be documented more clearly?

**Comment by timoknapp** [comment] 2021-12-09 08:30
> I made it work again by adding "-jvm" to all my artifact names... maybe this should be documented more clearly?

Hi @Zordid how did you actually fix it? Did you add the `-jvm` suffix to the Maven artifact in the `pom.xml` or where did you put it?

**Comment by nomisRev** [comment] 2021-12-09 08:49
@timoknapp if you use `arrow-core-jvm` instead of `arrow-core` it should work, but we're trying to fix this regression issue.

For those who are interessted this is the fix: https://github.com/Kotlin/kotlinx.serialization/blob/master/gradle/publish-mpp-root-module-in-platform.gradle

**Comment by timoknapp** [comment] 2021-12-09 08:53
Hi @nomisRev ,

thanks for the info! I'll try `arrow-core-jvm` then. Would be really cool fixing this soon. Our Renovate dependency updates are going crazy at the moment about this version of arrrow 😂

**Comment by nomisRev** [comment] 2021-12-09 09:02
Oh yes, that is very annoying. This fix will be included in the next release!

**Comment by timoknapp** [comment] 2021-12-22 21:37
Hi @nomisRev ,

any news on the fix?

**Comment by i-walker** [comment] 2022-02-22 13:34
Duplicate of #2597, can we close this @Zordid the fix will be available once `1.1.0` is publish, but there are alpha version already working with this the latest being `1.0.3-alpha.12`

**Comment by i-walker** [comment] 2022-03-11 13:23
Please check out the maven template here https://github.com/arrow-kt/Arrow-Maven-Template, thanks for reporting this !

**Closed by i-walker** 2022-03-11 13:23 UTC
