### ISSUE TITLE
Resolve ambiguity on some sugar extension functions in Arrow

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1505] opened 2019-07-04 15:00 UTC
Currently in Arrow there are several instances of extension functions that attempt to augment a data type syntax. In many cases these extension functions refer to member in type classes and the functions are duplicated both the manually handwritten one and the extension projected one.

We need to list all extension functions that are ad-hoc added over syntax in the data type file outside of the instance or somewhere else and list them under each data type. This will allow us to determine which ones can be eliminated comparing them to the functions the type class already exports.

**Comment by aballano** [comment] 2020-01-24 14:17
After some talks here and there it seems that this ticket cannot be resolved yet until we got Meta. 

The problem is that the current processor can either generate the instances for a specific one (like we have now) or traverse the whole data type parents and generate those (something that we used to do in the past i believe), which wasn't optimal either as we would need a marker to indicate where to stop somehow, or otherwise it'll derive up to Any/Object.

**Comment by raulraja** [comment] 2021-07-30 08:34
Closing this one as this processor is no longer part of Arrow. Thanks, @JorgeCastilloPrz @aballano

**Closed by raulraja** 2021-07-30 08:34 UTC
Labels: arrow-meta, blocked, enhancement
