### ISSUE TITLE
MonadSuspendCancellableContinuations.kt shows a lot of compilation warnings

### ISSUE THREAD

**Issue by jereksel** [arrow-kt/arrow#939] opened 2018-07-15 22:00 UTC
```
w: D:\MojeProgramy\arrow\modules\effects\arrow-effects\src\main\kotlin\arrow\effects\typeclasses\MonadSuspendCancellableContinuations.kt: (20, 6): Delegated member 'fun <A, B> Kind<F#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation), A#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.tupleLeft)>.tupleLeft(b: B#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.tupleLeft)): Kind<F#1, Tuple2<B#1, A#1>>' hides supertype override: public open fun <A, B> Kind<F#2 (type parameter of arrow.typeclasses.MonadErrorContinuation), A#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.tupleLeft)>.tupleLeft(b: B#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.tupleLeft)): Kind<F#2, Tuple2<B#2, A#2>> defined in arrow.typeclasses.MonadErrorContinuation. Please specify proper override explicitly
w: D:\MojeProgramy\arrow\modules\effects\arrow-effects\src\main\kotlin\arrow\effects\typeclasses\MonadSuspendCancellableContinuations.kt: (20, 6): Delegated member 'fun <A, B> Kind<F#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation), A#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.tupleRight)>.tupleRight(b: B#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.tupleRight)): Kind<F#1, Tuple2<A#1, B#1>>' hides supertype override: public open fun <A, B> Kind<F#2 (type parameter of arrow.typeclasses.MonadErrorContinuation), A#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.tupleRight)>.tupleRight(b: B#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.tupleRight)): Kind<F#2, Tuple2<A#2, B#2>> defined in arrow.typeclasses.MonadErrorContinuation. Please specify proper override explicitly
w: D:\MojeProgramy\arrow\modules\effects\arrow-effects\src\main\kotlin\arrow\effects\typeclasses\MonadSuspendCancellableContinuations.kt: (20, 6): Delegated member 'fun <A> Kind<F#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation), A#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.void)>.void(): Kind<F#1, Unit>' hides supertype override: public open fun <A> Kind<F#2 (type parameter of arrow.typeclasses.MonadErrorContinuation), A#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.void)>.void(): Kind<F#2, Unit> defined in arrow.typeclasses.MonadErrorContinuation. Please specify proper override explicitly
w: D:\MojeProgramy\arrow\modules\effects\arrow-effects\src\main\kotlin\arrow\effects\typeclasses\MonadSuspendCancellableContinuations.kt: (20, 6): Delegated member 'fun <B, A : B#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.widen)> Kind<F#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation), A#1 (type parameter of arrow.effects.typeclasses.MonadDeferCancellableContinuation.widen)>.widen(): Kind<F#1, B#1>' hides supertype override: public open fun <B, A : B#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.widen)> Kind<F#2 (type parameter of arrow.typeclasses.MonadErrorContinuation), A#2 (type parameter of arrow.typeclasses.MonadErrorContinuation.widen)>.widen(): Kind<F#2, B#2> defined in arrow.typeclasses.MonadErrorContinuation. Please specify proper override explicitly
```

**Comment by raulraja** [comment] 2018-07-15 22:04
I think we will benefit from moving the `binding` syntax outside of being an extension to be an actual method in `Monad` and their corresponding sub types. The reason is that as discussed with @Takhion `@instance` is going to generate specialized extensions based on the type class definition for the implementing data type and that will give us specialized versions of `binding` as well that don't need to be downcasted via `fix()` // cc @pakoito

**Comment by raulraja** [comment] 2018-07-15 22:06
We plan on pushing that syntax enhacement out in 0.8.0 where you will no longer need the `ForX extensions` since all data types will have the syntax baked in as part of the `@instance` codegen phase.

**Comment by pakoito** [comment] 2018-07-16 01:05
That class is long due for a refactor, that'll undertake at some point soon :D There was an attempt in an old effects branch.

**Comment by pakoito** [comment] 2019-04-04 22:55
Dupe of https://github.com/arrow-kt/arrow/issues/219

**Closed by pakoito** 2019-04-04 22:55 UTC
Labels: enhancement
