### ISSUE TITLE
SetK combineAll leads to StackOverflow

### ISSUE THREAD

**Issue by mervyn-mccreight** [arrow-kt/arrow#1717] opened 2019-10-16 09:20 UTC
**Code example for the issue**
```kotlin
import arrow.core.SetK
import arrow.core.extensions.setk.monoid.monoid

fun main() {
    val result: Set<Int> = SetK.monoid<Int>().run {
        listOf(
            SetK.just(1),
            SetK.just(2)
        ).combineAll()
    }

    println(result)
}
```

**Expected result**
`SetK(set=[1, 2])`

**Actual result** 
```
Exception in thread "main" java.lang.StackOverflowError
	at arrow.core.extensions.SetKMonoid$DefaultImpls.plus(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.SetKSemigroup$DefaultImpls.combine(setk.kt:26)
	at arrow.core.extensions.SetKMonoid$DefaultImpls.combine(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.typeclasses.Semigroup$DefaultImpls.plus(Semigroup.kt:15)
	at arrow.typeclasses.Monoid$DefaultImpls.plus(Monoid.kt)
	at arrow.core.extensions.SetKMonoid$DefaultImpls.plus(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.SetKSemigroup$DefaultImpls.combine(setk.kt:26)
	at arrow.core.extensions.SetKMonoid$DefaultImpls.combine(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.typeclasses.Semigroup$DefaultImpls.plus(Semigroup.kt:15)
	at arrow.typeclasses.Monoid$DefaultImpls.plus(Monoid.kt)
```

**Arrow version**: `0.10.0`

**Hint**
With ListK this is working just fine.

```kotlin
import arrow.core.ListK
import arrow.core.extensions.listk.monoid.monoid

fun main() {
    val result: List<Int> = ListK.monoid<Int>().run {
        listOf(
            ListK.just(1),
            ListK.just(2)
        ).combineAll()
    }

    println(result)
}
```

Results in `ListK(list=[1, 2])`

**Comment by pakoito** [comment] 2019-10-16 10:20
Someone reported this on the channels. I thought I'd open a ticket.

The issue is that, in here: https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/setk.kt#L26

Plus is defined in terms of combine, so it SOs.

**Comment by devesh-shetty** [comment] 2019-10-20 17:28
Fixed with https://github.com/arrow-kt/arrow/pull/1705

**Closed by devesh-shetty** 2019-10-20 17:28 UTC
