### ISSUE TITLE
Code samples not shown on desktop browsers(Chrome, FF....)

### ISSUE THREAD

**Issue by iguissouma** [arrow-kt/arrow#1176] opened 2018-12-05 13:25 UTC
Hello,

Code sample are not shown on the site:
[https://arrow-kt.io/docs/patterns/error_handling/](https://arrow-kt.io/docs/patterns/error_handling/)

![2018-12-05_14h17_28](https://user-images.githubusercontent.com/9085108/49516082-ff7e8800-f898-11e8-9029-05cbadeda844.png)

I'm not sure if it's intentionally but it's due to commented css property display: none; on language-kotlin class 

```
.language-kotlin {
  /* display: none; */
  }
```

Somehow on the browser this commented property is considered as active, disabling this property, the samples are shown.

![2018-12-05_14h17_39](https://user-images.githubusercontent.com/9085108/49516234-6bf98700-f899-11e8-8e9c-f62ddcf78078.png)

Thanks

**Comment by calvellido** [comment] 2018-12-07 12:55
Hi @iguissouma, thanks for reporting this. I'm having a look into this but, at least at the moment, I am correctly seeing the snippets and not able to reproduce it, could you please share some more information?

* Did you see any network error when this happened?
* Since you mention Chrome and Firefox, could you also share the OS and browser versions where this happened to you?
* Do you use some kind of ad blocker?
* It is always happening to you no matter the conditions you browse the docs?

The CSS property is expected behaviour as the code snippets are rendered through CodeMirror, which hides previous content replacing it by the CM content.

Thanks!

**Comment by iguissouma** [comment] 2018-12-07 16:32
Hello @calvellido 

I see a network error:

![image](https://user-images.githubusercontent.com/9085108/49659998-ca636880-fa45-11e8-891f-b823bc799d03.png)

![image](https://user-images.githubusercontent.com/9085108/49659932-9c7e2400-fa45-11e8-9275-f74184c1da09.png)

The problem is seen on our company network maybe it's due to security restrictions.

Thanks.

**Comment by JorgeCastilloPrz** [comment] 2018-12-07 17:18
Sounds very possible

**Comment by raulraja** [comment] 2018-12-07 18:05
Nobody seems to be able to repro. Closing this now. Feel free to reopen if it happens in the wild in an unrestricted network.

**Closed by raulraja** 2018-12-07 18:05 UTC
